import { Config, DEFAULT_CONFIG } from './types';

export interface SettingsPreset {
  id: string;
  name: string;
  description: string;
  settings: Partial<Config>;
}

export function resolveSettingsPresetConfig(preset: SettingsPreset): Config {
  return { ...DEFAULT_CONFIG, ...preset.settings };
}

export const SETTINGS_PRESETS: SettingsPreset[] = [
  {
    id: 'default',
    name: 'Default Config',
    description: 'Default settings. High growth, locomotor-favored.',
    settings: { ...DEFAULT_CONFIG },
  },
  {
    id: 'high-consumption-mobile',
    name: 'High-Consumption Mobile',
    description: 'Very high nutrient consumption, high locomotion.',
    settings: {
      photosynthesisRate: 4.1,
      environmentNutrientPhotosynthMinMultiplier: 0.78,
      environmentNutrientConsumptionRate: 1.19,
      locomotorFoodCost: 0.0009,
      impulseNutrientDemandRate: 0.0018,
      environmentLocomotorNutrientToFoodScale: 14.4,
      attackDamagePerLength: 4.5,
      foodStealPerDamage: 1.4,
      locomotorImpulsePerLength: 144,
      environmentNutrientRegenRate: 0.41,
      environmentFootprintScale: 1.85,
    },
  },
  {
    id: 'zero-consumption-hunter',
    name: 'Zero-Consumption Hunter',
    description: 'High attack, high locomotion, high nutrient availability.',
    settings: {
      photosynthesisRate: 8.5,
      environmentNutrientPhotosynthMinMultiplier: 0.67,
      environmentNutrientConsumptionRate: 0,
      locomotorFoodCost: 0.0016,
      impulseNutrientDemandRate: 0.002,
      environmentLocomotorNutrientToFoodScale: 26.75,
      attackDamagePerLength: 15,
      foodStealPerDamage: 0.3,
      locomotorImpulsePerLength: 164,
      environmentNutrientRegenRate: 0.68,
      environmentFootprintScale: 1.85,
    },
  },
  {
    id: 'photosynthesis-dominant',
    name: 'Photosynthesis Dominant',
    description: 'High photosynthesis, low locomotion cost.',
    settings: {
      photosynthesisRate: 10.1,
      environmentNutrientPhotosynthMinMultiplier: 0.72,
      environmentNutrientConsumptionRate: 0.775,
      locomotorFoodCost: 0.0001,
      impulseNutrientDemandRate: 0.0052,
      environmentLocomotorNutrientToFoodScale: 8.5,
      attackDamagePerLength: 9.2,
      foodStealPerDamage: 0.5,
      locomotorImpulsePerLength: 46,
      environmentNutrientRegenRate: 0.07,
      environmentFootprintScale: 0.45,
    },
  },
  {
    id: 'high-combat',
    name: 'High Combat',
    description: 'Very high attack (17.2), moderate locomotion.',
    settings: {
      photosynthesisRate: 5.7,
      environmentNutrientPhotosynthMinMultiplier: 0.78,
      environmentNutrientConsumptionRate: 1.375,
      locomotorFoodCost: 0.0003,
      impulseNutrientDemandRate: 0.0016,
      environmentLocomotorNutrientToFoodScale: 21.5,
      attackDamagePerLength: 17.2,
      foodStealPerDamage: 0.7,
      locomotorImpulsePerLength: 144,
      environmentNutrientRegenRate: 0.11,
      environmentFootprintScale: 1.85,
    },
  },
  {
    id: 'mobile-swarm',
    name: 'Mobile Swarm',
    description: 'Maximum locomotion (200), low footprint, aggressive.',
    settings: {
      photosynthesisRate: 3.9,
      environmentNutrientPhotosynthMinMultiplier: 0.16,
      environmentNutrientConsumptionRate: 0.3,
      locomotorFoodCost: 0.0061,
      impulseNutrientDemandRate: 0.0028,
      environmentLocomotorNutrientToFoodScale: 17.75,
      attackDamagePerLength: 13.8,
      foodStealPerDamage: 1.3,
      locomotorImpulsePerLength: 200,
      environmentNutrientRegenRate: 0.04,
      environmentFootprintScale: 0.3,
    },
  },
  {
    id: 'defender-fortress',
    name: 'Defender Fortress',
    description: 'High attack and locomotion with moderate defense.',
    settings: {
      photosynthesisRate: 5.7,
      environmentNutrientPhotosynthMinMultiplier: 0.78,
      environmentNutrientConsumptionRate: 1.375,
      locomotorFoodCost: 0.0003,
      impulseNutrientDemandRate: 0.0016,
      environmentLocomotorNutrientToFoodScale: 21.5,
      attackDamagePerLength: 17.2,
      foodStealPerDamage: 0.7,
      locomotorImpulsePerLength: 144,
      environmentNutrientRegenRate: 0.11,
      environmentFootprintScale: 1.85,
    },
  },
  {
    id: 'maximum-entropy',
    name: 'Maximum Entropy',
    description: 'Maximum locomotion (238), zero locomotor cost, highest entropy.',
    settings: {
      photosynthesisRate: 12.5,
      environmentNutrientPhotosynthMinMultiplier: 0.83,
      environmentNutrientConsumptionRate: 1.65,
      locomotorFoodCost: 0,
      impulseNutrientDemandRate: 0.003,
      environmentLocomotorNutrientToFoodScale: 12.75,
      attackDamagePerLength: 0.2,
      foodStealPerDamage: 1.1,
      locomotorImpulsePerLength: 238,
      environmentNutrientRegenRate: 0.51,
      environmentFootprintScale: 2.1,
    },
  },
  {
    id: 'scarcity-dynamics',
    name: 'Scarcity Dynamics',
    description: 'Very low photosynthesis, balanced movement.',
    settings: {
      photosynthesisRate: 0.9,
      environmentNutrientPhotosynthMinMultiplier: 0.69,
      environmentNutrientConsumptionRate: 0.25,
      locomotorFoodCost: 0.0017,
      impulseNutrientDemandRate: 0.0032,
      environmentLocomotorNutrientToFoodScale: 5.75,
      attackDamagePerLength: 1.6,
      foodStealPerDamage: 0.4,
      locomotorImpulsePerLength: 88,
      environmentNutrientRegenRate: 0.13,
      environmentFootprintScale: 2.05,
    },
  },
  {
    id: 'sustained-growth',
    name: 'Sustained Growth',
    description: 'Low attack, suppressed locomotion, high food conversion efficiency.',
    settings: {
      photosynthesisRate: 8.3,
      environmentNutrientPhotosynthMinMultiplier: 0.03,
      environmentNutrientConsumptionRate: 2.6,
      locomotorFoodCost: 0.0003,
      impulseNutrientDemandRate: 0.0044,
      environmentLocomotorNutrientToFoodScale: 29,
      attackDamagePerLength: 4,
      foodStealPerDamage: 0.7,
      locomotorImpulsePerLength: 14,
      environmentNutrientRegenRate: 0.54,
      environmentFootprintScale: 1.4,
    },
  },
  {
    id: 'hyperlocomotive',
    name: 'Hyperlocomotive',
    description: 'Maximum locomotion, high attack, full population capacity.',
    settings: {
      photosynthesisRate: 8.8,
      environmentNutrientPhotosynthMinMultiplier: 0.88,
      environmentNutrientConsumptionRate: 0.7,
      locomotorFoodCost: 0.0004,
      impulseNutrientDemandRate: 0.0014,
      environmentLocomotorNutrientToFoodScale: 26.25,
      attackDamagePerLength: 16.4,
      foodStealPerDamage: 2.5,
      locomotorImpulsePerLength: 214,
      environmentNutrientRegenRate: 0.09,
      environmentFootprintScale: 1,
    },
  },
  {
    id: 'aggressive-harvester',
    name: 'Aggressive Harvester',
    description: 'High attack, maximum food steal, producer-dominant ecosystem.',
    settings: {
      photosynthesisRate: 12.5,
      environmentNutrientPhotosynthMinMultiplier: 0.11,
      environmentNutrientConsumptionRate: 2.25,
      locomotorFoodCost: 0.0048,
      impulseNutrientDemandRate: 0.0074,
      environmentLocomotorNutrientToFoodScale: 22,
      attackDamagePerLength: 17.8,
      foodStealPerDamage: 4.9,
      locomotorImpulsePerLength: 12,
      environmentNutrientRegenRate: 0.19,
      environmentFootprintScale: 2.25,
    },
  },
  {
    id: 'max-attack',
    name: 'Max Attack',
    description: 'Very high attack, high nutrient regeneration, strong role coexistence.',
    settings: {
      photosynthesisRate: 9.8,
      environmentNutrientPhotosynthMinMultiplier: 0.55,
      environmentNutrientConsumptionRate: 0.15,
      locomotorFoodCost: 0.0089,
      impulseNutrientDemandRate: 0.0064,
      environmentLocomotorNutrientToFoodScale: 20.25,
      attackDamagePerLength: 19.6,
      foodStealPerDamage: 0.1,
      locomotorImpulsePerLength: 42,
      environmentNutrientRegenRate: 0.89,
      environmentFootprintScale: 1.2,
    },
  },
  {
    id: 'zero-regen',
    name: 'Zero Regen',
    description: 'High attack, zero nutrient regeneration, entities must compete for resources.',
    settings: {
      photosynthesisRate: 13.1,
      environmentNutrientPhotosynthMinMultiplier: 0.44,
      environmentNutrientConsumptionRate: 1.275,
      locomotorFoodCost: 0.0017,
      impulseNutrientDemandRate: 0.002,
      environmentLocomotorNutrientToFoodScale: 28.25,
      attackDamagePerLength: 18.2,
      foodStealPerDamage: 0.9,
      locomotorImpulsePerLength: 132,
      environmentNutrientRegenRate: 0,
      environmentFootprintScale: 2.35,
    },
  },
  {
    id: 'balanced',
    name: 'Balanced',
    description: 'Moderate values across all parameters, balanced ecosystem dynamics.',
    settings: {
      photosynthesisRate: 5.5,
      environmentNutrientPhotosynthMinMultiplier: 0.61,
      environmentNutrientConsumptionRate: 0.575,
      locomotorFoodCost: 0.0004,
      impulseNutrientDemandRate: 0.0012,
      environmentLocomotorNutrientToFoodScale: 7,
      attackDamagePerLength: 5.4,
      foodStealPerDamage: 1.7,
      locomotorImpulsePerLength: 138,
      environmentNutrientRegenRate: 0.01,
      environmentFootprintScale: 1.05,
    },
  },
];
